### PR TITLE
Add Upgrade connection headers to allow websockets

### PR DESCRIPTION
**Pull request by nicofrand**
Websockets are not working right now, this PR should fix it.

### CODE REVIEW

**Comment by opi** [comment]
( I don't know very much about websocket )

Does adding this configuration line can mess up for non-websocket apps ? Maybe we could add an option during redirect_ynh installation ?

**Comment by nicofrand** [comment]
I guess not: http://nginx.org/en/docs/http/websocket.html.

> Since version 1.3.13, nginx implements special mode of operation that allows setting up a tunnel between a client and proxied server if the proxied server returned a response with the code 101 (Switching Protocols), and **the client asked** for a protocol switch via the “Upgrade” header in a request.

If the app does not use websockets, then the client will no ask for a protocol switch.

But an option is always cool.

**Comment by scith** [comment]
I am not in favor of extra options, especially if these are difficult to understand.

- If websockets can cause security concerns while solving only very specific use cases, then we should explain in the readme how to active the option
- If not (no big security concern or wide applications), then we should activate it by default and put a warning in the readme

What do you think? I don't know enough about websockets to choose between the two

**Comment by nicofrand** [comment]
I never met any issue with it and I don't why there should be (given previous documentation link) so the second solution looks fine to me…

> while solving only very specific use cases
FYI, most of the apps I use with redirect use websockets (my own TheLounge, cozy, ...).

**Comment by Psycojoker** [comment]
Websockets are just "another protocol" to do website, they won't add more security vulnerabilities than any other protocol, this is the app responsibility.

Activate them on an app that doesn't support them normally won't do anything (since you need the backend to be compatible with them, nginx is only a transport layer there).

I have troubles seeing a reason not to accept this PR. If it's really a problem you can add an option in the installation script to activate them.

**Comment by opi** [comment]
ok then (https://www.youtube.com/watch?v=_EX9UQ0SJG8)

**Comment by scith** [comment]
Cool thanks for the explanations

**Pull request merged**
